### PR TITLE
feat: Dockerize: Add Dockerfile, docker-compose. change 127.0.0.1 to …

### PR DESCRIPTION
**Pull request by dermatologist**
Changes:
Dockerize: Add Dockerfile, docker-compose. 
change 127.0.0.1 to db (container name).   [BREAKING CHANGE]
Change ctakes to v 4.0.0 and 
upgrade version of mysql connector.

### CODE REVIEW

**Comment by MatthewVita** [comment]
Hi @dermatologist,

Thanks for putting this together! A few notes/questions:

- What is `beapen/ctakes` ?

- Is it possible to copy ctakes-web-rest/src/main/resources/org/apache/ctakes/dictionary/lookup/fast/customDictionary.xml into the container and do a string replace to `db` so we don't have to alter the original xml file?

- Not sure if you saw https://github.com/GoTeamEpsilon/ctakes-rest-service/issues/65 but, if you did, do you see better results with things running in Docker?

- I'll add the docs for building/running docker-compose once this is in. I wonder if it be the standard for this repo in general to remove build issues that pop up here and there.

Thanks!
Matthew

**Comment by dermatologist** [comment]
Hi @MatthewVita 

beapen/ctakes is the name of the image that will be created locally. You can replace it with any name you wish.

Please ignore this PR. [I have a solution](https://github.com/E-Health/ctakes-rest-service) for 2 and 3 above in your comments. I will submit another PR soon after some more cleanup. 

Cheers!

**Comment by MatthewVita** [comment]
@dermatologist,

That sounds great. Let me know what I can do!

**Comment by MatthewVita** [comment]
Hi @dermatologist - was wondering what your status was on the docker solution or if this is something you can hand off? No pressure or anything, of course!

Once we have docker(compose) in place, it will likely be the main way to run this solution. There have been so many install road bumps for a lot of ppl across different system types.

EDIT: I would be rude not to mention that I hope you and your loved ones are doing well during the pandemic.

**Comment by dermatologist** [comment]
Hi @MatthewVita

Sorry, I missed this. I followed a slightly different route using quarkus, which surprisingly worked very well, and it is fast. It is here: https://github.com/dermatologist/quick-ctakes 

Thanks for the wishes, and stay safe and healthy!

**Pull request closed without merging**
